services:
  app:
    image: todo-react-frontend-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3000
    container_name: todo-react-frontend-dev #
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
  debug-helper:
    image: busybox
